# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53d4d85421fd3f7c05ceff04d7cd88f919734da57ad8dc8f86cecdf34f21dcf98ae2cbdf485c21ce68381ecf57d73c9efe965c1730aeae88a925f4d9d43f7172

test:
  secret_key_base: 1cb749b4358c3a8d67e3f0e8a12928df363464e2fef05ab79809103eaa02fda1c2c297c8c0058c2c2a7d709a4da3bcfe60940fa738eac3835787b3fa171652da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
